Repository devRant-Community/Community-Programming-Book, pull requests merged in 2018-05, with the labels that each got.

#11 Adding Gitbook
  CONTRIBUTING.md
  book.json
  book/Summary.md
  book/intro.md
  book/welcome.md
  intro.md
Labels: enhancement

#6 C++ - Chapter
  book/SUMMARY.md
  book/languages/cpp/README.md
  book/languages/cpp/intro.md
Labels: new-chapter

#22 Added Icons in SVG & PNG
  book/icons/png/Assembly.png
  book/icons/png/Assembly@2x.png
  book/icons/png/C#.png
  book/icons/png/C#@2x.png
  book/icons/png/C++.png
  book/icons/png/C++@2x.png
  book/icons/png/C.png
  book/icons/png/C@2x.png
  book/icons/png/JavaScript.png
  book/icons/png/JavaScript@2x.png
  book/icons/png/Kotlin.png
  book/icons/png/Kotlin@2x.png
  book/icons/png/Python.png
  book/icons/png/Python@2x.png
  book/icons/svg/Assembly.svg
  book/icons/svg/C#.svg
  book/icons/svg/C++.svg
  book/icons/svg/C.svg
  book/icons/svg/JavaScript.svg
  book/icons/svg/Kotlin.svg
  book/icons/svg/Python.svg
Labels: Design

#25 Assembly and Python- Chapter
  book/SUMMARY.md
  book/languages/assembly/README.md
  book/languages/assembly/advantages.md
  book/languages/assembly/conclusion.md
  book/languages/assembly/disadvantages.md
  book/languages/assembly/history.md
  book/languages/assembly/intro.md
  book/languages/assembly/what_it_solves.md
  book/languages/python/README.md
  book/languages/python/advantages.md
  book/languages/python/conclusion.md
  book/languages/python/disadvantages.md
  book/languages/python/history.md
  book/languages/python/intro.md
  book/languages/python/misc.md
  book/languages/python/what_it_solves.md
Labels: new-chapter
