Repository devRant-Community/Community-Programming-Book, pull requests merged in 2019-02, with the labels that each got.

#50 Add Haskell part
  book/SUMMARY.md
  book/credits.md
  book/languages/cpp/advantages.md
  book/languages/cpp/conclusion.md
  book/languages/cpp/disadvantages.md
  book/languages/cpp/history.md
  book/languages/cpp/intro.md
  book/languages/erlang/README.md
  book/languages/erlang/conclusion.md
  book/languages/golang/README.md
  book/languages/golang/conclusion.md
  book/languages/haskell/README.md
  book/languages/haskell/advantages.md
  book/languages/haskell/conclusion.md
  book/languages/haskell/disadvantages.md
  book/languages/haskell/history.md
  book/languages/haskell/intro.md
  book/languages/haskell/misc.md
  book/languages/js/README.md
  book/languages/js/conclusion.md
Labels: enhancement, help wanted, new-chapter

#54 Brainfuck part
  book/SUMMARY.md
  book/credits.md
  book/languages/brainfuck/README.md
  book/languages/brainfuck/advantages.md
  book/languages/brainfuck/conclusion.md
  book/languages/brainfuck/disadvantages.md
  book/languages/brainfuck/history.md
  book/languages/brainfuck/intro.md
Labels: enhancement, new-chapter

#55 Small fixes regarding Assembly
  book/languages/assembly/advantages.md
  book/languages/assembly/disadvantages.md
  book/languages/assembly/what_it_solves.md
Labels: enhancement, help wanted, improve-chapter

#58 Malbolge part
  book/SUMMARY.md
  book/languages/brainfuck/disadvantages.md
  book/languages/malbolge/README.md
  book/languages/malbolge/advantages.md
  book/languages/malbolge/conclusion.md
  book/languages/malbolge/disadvantages.md
  book/languages/malbolge/history.md
  book/languages/malbolge/intro.md
Labels: enhancement, help wanted, new-chapter

#59 Perl
  book/languages/perl/README.md
  book/languages/perl/advantages.md
  book/languages/perl/conclusion.md
  book/languages/perl/disadvantages.md
  book/languages/perl/history.md
  book/languages/perl/intro.md
Labels: enhancement, help wanted, new-chapter

#60 C part
  .mdlintrc
  book/SUMMARY.md
  book/languages/c/README.md
  book/languages/c/advantages.md
  book/languages/c/conclusion.md
  book/languages/c/disadvantages.md
  book/languages/c/history.md
  book/languages/c/intro.md
Labels: enhancement, help wanted, new-chapter
